### ISSUE TITLE
Release the second Alpha version with Netty 5.0.0.Alpha5

### ISSUE THREAD

**Issue by violetagg** [netty-contrib/codec-extras#18]
@chrisvest @normanmaurer We already have Netty 5.0.0.Alpha5 released. What do you think about releasing the second Alpha version for this module?

**Comment by chrisvest** [comment]
@violetagg Sounds like a good idea. Do you see the "Run workflow" button on the "Release" workflow? If so, do you want to give it a try?

**Comment by violetagg** [comment]
@chrisvest I was able to release. Thanks!

**Comment by chrisvest** [comment]
Awesome!
